#!/bin/zsh

installs() {
    brew install --cask font-fira-code-nerd-font
    brew install bat starship tmux
}

optional_installs() {
    brew install --cask session-manager-plugin
    brew install awscli curl fish imagemagick nvm python3 redis tmux wget
    brew install gpg2 gnupg pinentry-mac
}

setup_links() {
    mkdir -p ~/.config/git ~/.local/share/sendssh
    ln -sfn "$(pwd)/zsh/.zshenv" ~/.zshenv
    ln -sfn "$(pwd)/zsh" ~/.config/zsh
    ln -sfn "$(pwd)/config/git.config" ~/.config/git/config
    ln -sfn "$(pwd)/config/bat.config" ~/.config/bat.conf
    ln -sfn "$(pwd)/sendssh/data" ~/.local/share/sendssh/data
}

echo "================================================"
echo "= This script will download and install some   ="
echo "= cool stuff and create symlinks for your      ="
echo "= dotfiles in this repo.                       ="
echo "================================================"


echo "Do you wish to continue to the download and install?"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) installs; break;;
        No ) break;;
    esac
done

echo "Do you wish to continue to the optional installs?"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) optional_installs; break;;
        No ) break;;
    esac
done

echo "Do you wish to continue to the setup of symlinks?"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) setup_links; break;;
        No ) break;;
    esac
done