# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format= """
$username\
$hostname\
$jobs\
$directory\
$git_branch\
$git_status\
$python\
$sudo\
$status\
$container\
$character"""

[username]
format = '[$user]($style)'

[hostname]
format = '@[$hostname]($style)'

[sudo]
disabled = false

[git_branch]
format = '[\($branch(:$remote_branch)\) ]($style)'

[python]
format = '[(\($virtualenv\) )]($style)'
