# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format= """
$username\
$hostname\
$jobs\
$directory\
$aws\
$git_branch\
$git_status\
$nodejs\
$python\
$sudo\
$status\
$container\
$character"""

[username]
format = '[$user]($style)'

[hostname]
format = '@[$hostname]($style)'

[sudo]
disabled = false

[aws]
format = '[($profile )(\($region\) )(\[$duration\] )]($style)'
[aws.region_aliases]
us-east-2 = ''

[git_branch]
format = '[\($branch(:$remote_branch)\) ]($style)'

[python]
format = '[(\($virtualenv\) )]($style)'

[nodejs]
format = '[\(($version)\) ]($style)'
version_format = 'v${major}.${minor}'
